training:
  lr: 0.0001
  weight-decay: 0.00001
  bs: 16
  scheduler: 'ReduceLROnPlateau'
  gamma: 0.1
  step-size: 15
  rebalancing_fake: 0.3
  rebalancing_real: 1
  frames-per-video: 3 # Equidistant frames
  
model:
  image-size: 224
  patch-size: 7
  num-classes: 1
  dim: 256
  depth: 3
  dim-head: 64
  heads: 2
  mlp-dim: 1024
  emb-dim: 32
  dropout: 0.3
  emb-dropout: 0.3