training:
  lr: 0.0001
  weight-decay: 0.0000001
  bs: 16
  scheduler: 'steplr'
  gamma: 0.1
  step-size: 15
  rebalancing_fake: 0.3
  rebalancing_real: 1
  frames-per-video: 5 # Equidistant frames
  
model:
  image-size: 224
  patch-size: 7
  num-classes: 1
  dim: 512
  depth: 4
  dim-head: 64
  heads: 4
  mlp-dim: 2048
  emb-dim: 32
  dropout: 0.15
  emb-dropout: 0.15