
name: deepfakes2
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio
  - jupyterlab
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib
  - scipy=1.10.1
  - scikit-learn=1.2.2
  - tensorflow=2.11.0
  - tensorflow-estimator=2.11.0
  - h5py
  - tqdm=4.65.0
  - pillow=9.4.0
  - imageio
  - requests=2.31.0
  - pyyaml=6.0
  - protobuf
  - pip:
      - opencv-python
      - stylegan2-pytorch==1.8.4
      - timesformer-pytorch==0.3.2
      - vit-pytorch==0.18.3
      - lightweight-gan==0.20.4
      - kornia==0.6.12
      - py3nvml==0.2.6
      - yacs==0.1.8
      - facenet_pytorch==2.6.0
      - efficientnet-pytorch==0.7.1
      - progress==1.5
      - albumentations
